### PR TITLE
MAINT: Change saved array `dtype` to `uint8`

### PR DESCRIPTION
**Pull request by AnirudhDagar**
xref https://github.com/scipy/scipy/pull/17606#issuecomment-1353471670

This will also mean that the file hash has changed, and registry in scipy.datasets._registry.py needs to be updated with new hash: `03ce124c1afc880f87b55f6b061110e2e1e939679184f5614e38dacc6c1957e2`

cc @rgommers

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
Please note that as soon as this is merged, I'd expect a broken CI in SciPy. So we can wait for update on https://github.com/scipy/scipy/pull/17606 and once we merge that, then let's get this in.

**Comment by rgommers** [comment]
Sounds good, thanks Anirudh. 259kb less is a nice benefit

**Comment by tylerjereddy** [comment]
Let's get this stuff rolling I think--I commented in the main repo PR--if that does't get updated very soon, probably best to just open a new PR with the changes you want, and co-credit the original author maybe.

**Comment by rgommers** [comment]
Thanks @AnirudhDagar! Let's give this a go

**Pull request merged**
